apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: localhost:5000/opus-books-api
    jibMaven: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.TAG}}"
deploy:
  helm:
    releases:
    - name: books-api
      chartPath: ../charts/books-api
      setValues:
        auth.htpassword: dXNlcjE6JGFwcjEkcHFTb3VWTE4kQ2EvQVNKSFhLU2dJSlpsd295andtMQ==
        ingress.enabled: false
        h2.enabled: false
        image.repository: localhost:5000/opus-books-api
        service.type: NodePort
      setValueTemplates:
        image.tag: "{{.TAG}}"