apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: registry.k8.wildwidewest.xyz/repository/docker-repository/opus/books-api
    jibMaven: {}
    #docker:
    #  dockerfile: Dockerfile
  #- image: 1000kit/h2
deploy:
  helm:
    releases:
    - name: books-api
      chartPath: ../charts/books-api
      setValues:
        auth.htpassword: dXNlcjE6JGFwcjEkcHFTb3VWTE4kQ2EvQVNKSFhLU2dJSlpsd295andtMQ==
      setValueTemplates:
        image.tag: "{{.DIGEST}}"
