logging:
  level:
    org:
      springframework:
        security: DEBUG


security:
  oauth2:

    resource:
      user-info-uri: https://keycloak.k8.wildwidewest.xyz/auth/realms/opus/protocol/openid-connect/userinfo
      token-info-uri: https://keycloak.k8.wildwidewest.xyz/auth/realms/opus/protocol/openid-connect/token/introspect
      prefer-token-info: false

    client:
      client-id: books-api
      access-token-uri: https://keycloak.k8.wildwidewest.xyz/auth/realms/opus/protocol/openid-connect/token
      user-authorization-uri: https://keycloak.k8.wildwidewest.xyz/auth/realms/opus/protocol/openid-connect/auth
      scope: openid
      client-secret: "1b56dd14-fc57-4fd5-903a-bc59aabcab4c"
      grant-type: authorization_code